# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: install requirements
        run: |
          pip3 install -r py/requirements.txt
          pip3 install pyinstaller
      
      - name: build py exe
        run: |
          pyinstaller -F py/api_server.py
          cp .\dist\api_server.exe .\bin
      
      # step2: install node env
      - name: Install Node.js
        uses: actions/setup-node@v2-beta

      - name: build electron
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          build_script_name: electron:build

      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/
